<a href="https://colab.research.google.com/github/Phantom6Paradise7/Data_Science_2026/blob/main/Pandas_and_join_Day_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1757 question - Leetcode

In [23]:
import pandas as pd

In [14]:
dic = {
    "product_id" : [100,101,102,103],
    "low_fats" : ["Y","Y","N","Y"],
    "recyclable" : ["N","Y","Y","Y"]
}
df = pd.DataFrame(dic)
display(df)
Answer = (df['low_fats'] == 'Y') & (df['recyclable'] == 'Y')
print("Boolean Series 'Answer':")
print(Answer)
filtered_product_ids = df[Answer]['product_id']
print("\nProduct IDs where both conditions are true:")
print(filtered_product_ids)

   product_id low_fats recyclable
0         100        Y          N
1         101        Y          Y
2         102        N          Y
3         103        Y          Y

Boolean Series 'Answer':
0    False
1     True
2    False
3     True
dtype: bool

Product IDs where both conditions are true:
[[1    101
3    103
Name: product_id, dtype: int64]]

#584 question - Leetcode

In [19]:
dic = {
    "id" : [1,2,3,4,5,6],
    "name" : ["Will","Jane","Alex","Bill","Zack","Mark"],
    "referee_id" : [None , None , 2 , None , 1 , 2]
}
df = pd.DataFrame(dic)
display(df)
result_df = df[(df['referee_id'].isnull()) | (df['referee_id'] != 2)]
final_names = result_df[['name']]
display(final_names)

   id  name  referee_id
0   1  Will         NaN
1   2  Jane         NaN
2   3  Alex         2.0
3   4  Bill         NaN
4   5  Zack         1.0
5   6  Mark         2.0

   name
0  Will
1  Jane
3  Bill
4  Zack

#Continuing with pandas

In [33]:
df = pd.read_csv('student.csv')

In [34]:
df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1636
Placed        8333
Name: placement_status, dtype: int64

In [37]:
df.groupby('placement_status')['exam_score'].agg('mean')

placement_status
Not Placed    59.800954
Placed        91.998494
Name: exam_score, dtype: float64

In [38]:
df.groupby('placement_status')['exam_score'].mean()

placement_status
Not Placed    59.800954
Placed        91.998494
Name: exam_score, dtype: float64

In [39]:
df.groupby('exam_score')['study_hours'].sum()

exam_score
26.67         1
26.89         1
27.82         1
31.41         1
31.43         2
          ...
99.96         7
99.97         7
99.98        14
99.99        20
100.00    28438
Name: study_hours, Length: 3563, dtype: int64

In [57]:
def grades(score):
  if score >= 90:
    return 'A'
  elif score >= 80:
    return 'B'
  elif score >= 70:
    return 'C'
  elif score >= 60:
    return 'D'
  else:
    return 'E'

df['grade'] = df['exam_score'].apply(grades)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,grade
0,7,56,8,7,10,62,100.00,Placed,A
1,4,69,5,3,8,56,100.00,Placed,A
2,11,60,7,6,10,45,100.00,Placed,A
3,8,99,9,8,4,55,90.17,Placed,A
4,5,52,8,6,8,40,78.82,Placed,C
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,D
9996,7,98,6,9,4,87,100.00,Placed,A
9997,10,44,8,5,10,37,95.94,Placed,A
9998,10,75,7,5,8,52,88.61,Placed,B
9999,2,70,6,11,16,52,78.96,Placed,C